### ISSUE TITLE
Cant paint

### ISSUE THREAD

**Issue by MianiteWorlds** [Fupery/ArtMap#14]
every time i try to paint (right click whit a dye) it just moves me haf a block in the air and haf a block in a direction, doesnt let me paint

**Comment by Fupery** [comment]
Okay, sounds like the same issue - are there any errors in console? Either something about "renderer not found" or "failed to bind player channel"?

**Comment by Fupery** [comment]
Probably plugin compatibility issue. Haven't seen this reported by any other users.
