### ISSUE TITLE
Possible to spawn in player created artwork via a command?

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#26]
Hello, 

I was wondering if it was possible to spawn in player created artwork via a command? Idea would be to reward / give people specific map artwork like holiday themed images. Either by spawning in through artist's name with painting name or if all artwork had an internal number attached with it? Or by specific map ID the artwork is saved to?

**Comment by Fupery** [comment]
Sure, I'll add this functionality to the give command in the next update.

**Comment by Fupery** [comment]
This feature will be available in version 2.5.5
