### ISSUE TITLE
Canvas update is slow / delayed when painting.

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#29]
Is it possible at all to improve the speed the canvas is updated when painting? It seems to be slow and delayed. Server TPS is stable at ~20, so shouldn't be a server slowdown problem.

**Comment by mibby** [comment]
@Fupery The slow painting is dreadful. :( Is there no way to speed it up at all?

**Comment by Fupery** [comment]
Apologies for the delayed response - unfortunately the painting rate as it is has been heavily optimised; this is as fast as I could get it. The main cause of the delay is between the client -> server connection, which I unfortunately have no control over.

**Comment by mibby** [comment]
That's unfortunate to hear. :( Is there a specific packet you could hook into to speed it up if ProtocolLib is used? The update rate is tremendously slow to really be able to paint in real time.

**Comment by Fupery** [comment]
Yes, I'm very much aware of ProtocolLib (You might notice it says "[ArtMap] ProtocolLib hooks enabled." in console every time the plugin is loaded). 

I've done some benchmarking on drawing time: the time between the server receiving the player's input packets to a pixel being drawn on the map is 0.16 milliseconds, so this isn't the issue. However, after the map is updated, it looks like the server doesn't update the client immediately; I may be able to shave some time off by forcing the server to send a map every time the player clicks. This may work, but I'll have to do some tests to see if this has an impact on server performance.

**Comment by Fupery** [comment]
I've managed to improve painting speed considerably using the method I detailed above (sending more frequent update packets). It's been uploaded in version 2.5.2 👍

**Comment by mibby** [comment]
Thanks a lot! It is significantly faster from my quick testing.
