### ISSUE TITLE
ArtMap remove after save gives map + canvas

### ISSUE THREAD

**Issue by JerichoDiamond** [Fupery/ArtMap#3]
Fups - it happened again. I find this hard to reproduce, but after saving an artmap and go to remove it, I get a map, artmap, easle and armour stand. The map and armour stand are extras.

Not sure how to reproduce; but will try after finishing next painting.

**Comment by Fupery** [comment]
Alright I'll have a look and see if I can figure out what's happening, thanks.

**Comment by Fupery** [comment]
Easel event handling has been improved, and it looks like the issue has been resolved :)
