### ISSUE TITLE
Is there pagination for viewing artwork creations?

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#36]
What happens if there are hundreds of players who have created a painting? Or if one person has hundreds of artwork themselves? Is there a form of pagination in the GUI to scroll through an infinite number of players / saved artwork?

**Comment by Fupery** [comment]
Yes, the artwork list retrieved from the database is split into gui pages.

**Comment by mibby** [comment]
Wonderful, that is great news. As long as it dynamically can expand to infinite pages to support an unlimited amount of artwork from one player and many players listed in the menu.

**Comment by Fupery** [comment]
Yep, it's functionally infinite.
