### ISSUE TITLE
If someone disconnects from the server while using an easel, they (and admins) are unable to remove the easel.

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#38]
If someone disconnects from the server while using an easel, they (and admins) are unable to remove the easel or re-mount it to use it again. You get a "somebody else is already using this canvas" output.

I'm assuming the easel isn't clearing / dismounting the player entity when they disconnect. (User's client crashed.) Might want to make sure the easel rider state is properly reset if the player disconnects while on it or if they get forcefully teleported away from it.

**Comment by Fupery** [comment]
These checks are already in place, I'll have a look into it though. The bukkit disconnect events may not being thrown on a client crash.

**Comment by mibby** [comment]
👍  Any update on this issue (or any of the others)? I'm willing to help test fixes and new features. :)

**Comment by Fupery** [comment]
I've got updates/questions for you on a few of the others; I can't replicate this bug even when forcing a client crash, however. I'll keep testing.

**Comment by mibby** [comment]
I can't seem to reproduce this bug on the latest version but I'll reopen if I hear back from anyone that it is still occurring.
