### ISSUE TITLE
Player saved artwork is wiping and rendering random bits of terrain instead after some time. 

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#39]
ArtMap v2.5
Paper dev 996 (Spigot 1.11.2)

Hi @Fupery . Getting many reports from a seemingly random selection of ArtMap users that their saved artwork after some time is being reset and rendering random bits of terrain instead. I don't have any other plugins that would be overwriting the map ID. There are no errors in the console log or any new errors in the artmap error log.

Restarting the server to load the artmap database again didn't fix the maps from the affected players. However oddly enough, a player randomly tried re-saving their artwork and it appeared again. While another player tried re-editing it on an easel, it did not work, just broke. (See Easel re-edit bug / crash ticket. https://github.com/Fupery/ArtMap/issues/31)

**Comment by Fupery** [comment]
Try running /artmap restore <artwork title> on the affected artworks.

**Comment by mibby** [comment]
Thanks. I'll try running the command on the affected artwork and figure out what is happening if it occurs again. However, I believe I detected a fatal flaw in ArtMap that will soon cause a significant problem on my server. ArtMap is saving canvas map IDs based on the last ID available in the map_id.dat range.

I use this plugin to manage and convert images to a map board
https://www.spigotmc.org/resources/bannerboard.20435/

It reserves a range of map IDs and pre-generates the blank files.
```
idrange:
  startid: 25000
  amount: 5000
```

My map IDs from 0 to 5,246 are from vanilla generated and created maps. Then there is a significant gap. Then from map IDs 25,000 to 30,000, those are reserved by the BannerBoard plugin for server-use. All ArtMap canvas maps have been starting from ID 30,000 up to now 31,099. Minecraft has a hardcoded map limit of 32,768, so problems will ensue quite shortly.

Would it be possible for ArtMap to save map canvases based on the next available map ID rather than the last ID that exists? Or alternatively, being able to define a range similar to BannerBoard for map images to be used? Because at the current rate of players creating artwork, I will hit the map ID limit with thousands of map IDs not generated / used in-between the two chunk 'sets'.

---

Side-note. Would it be possible to implement a restore-all command in the event the map IDs somehow got overwritten?

**Comment by Fupery** [comment]
Ok, you're partly correct - ArtMap actually _does_ generate the next available map; it actually generates new maps the same way that vanilla Minecraft does.

However, when the Minecraft server is creating a new map, it doesn't look at all the maps that already exist, it just looks for the map id of the last map generated (found in the **world/data/idcounts.dat** file), and increment that number, ignoring all the unused map id's in between. So in fact any vanilla or ArtMap maps that you generate will be in the 30,000 range now.

---

So, this may be a bit tricky to fix - you'll need to:
1. Move your bannerboard range down to 5250 or something closer to your current max map id.
2. Use a NBT editor (I use [NBTexplorer](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac)) to open your 'idcounts.dat' file and change the number to the last id in your bannerboard range (so 5250 + 5000, for example).
3. [Optional] Somehow change the id's of all your ArtMap and vanilla maps in the 30,000 range to something closer to 5000 (so they aren't eventually overwritten if you eventually have 30,000 maps) - your "restore-all" command idea might be able to do this! I'll work on implementing it.

If you need any specific help with this stuff, I'm happy to provide more assistance. 😄 

---

Re: the other errors you linked, I'm working on an idea for some kind of autosave feature to combat these.

**Comment by Fupery** [comment]
The original issue should be fixed in version [2.6](https://www.spigotmc.org/resources/artmap-make-custom-textures-and-paintings-with-no-resource-pack-✍.26667/update?update=157774)
