### ISSUE TITLE
Coffee Colour = Obsidian

### ISSUE THREAD

**Issue by JerichoDiamond** [Fupery/ArtMap#4]
Utils/ArtDye.java line 28
Melon seeds is should be colour ID 42, not 138. 138 on 1.8 chart is obsidian. 138 on the map colour chart is dirt, which is where I think you got your wires crossed.

**Comment by Fupery** [comment]
Obsidian still renders as brown! The dirt colour has a bit more contrast to the brown dye though, so I've knocked it down to 41 to make it a bit more useful.
