### ISSUE TITLE
Gui left click drags out item - doesn't click

### ISSUE THREAD

**Issue by nunavailabul** [Fupery/ArtMap#40]
When going into the gui - instead of clicking the item and something happening - the item (sign, crafting table, rose, book, painting) are simply grabbed as though it were an inventory.

Have I Noobed the installation?

**Comment by Fupery** [comment]
Hey, are you getting any exceptions in console when trying to open the menu, or when you click? Do you have an error.log in your plugins/ArtMap folder?

**Comment by nunavailabul** [comment]
Hi Fupery, 

Apologies - I just realised how little info I gave you - I was super tired at the time.

I'm running CraftBukkit 1.11.2
API 1.11.2-R0.1-SNAPSHOT

In this console output I  I right clicked the easel before typing /artmap:
    Paste of error http://pastebin.com/W5JfMWMf

**Comment by Fupery** [comment]
Oh, you're running a CraftBukkit server? Unfortunately ArtMap relies fairly heavily on the Spigot API, so it's only compatible with Spigot servers.

**Comment by nunavailabul** [comment]
Hazzah!  Switched to Spigot 1.11.2.  TY TY

**Comment by Fupery** [comment]
Awesome, glad it's working.
