### ISSUE TITLE
Placing a saved ArtMap map back on a canvas does not throw off an update event to display the map on the Easel.

### ISSUE THREAD

**Issue by mibby** [Fupery/ArtMap#45]
ArtMap v2.5.7

You must sit on the easel and right click the canvas for the map to display again. Video example below.
https://www.dropbox.com/s/a6xbhcidhjvyb5b/2017-03-15%2001-12-52.mkv?dl=0

**Comment by Fupery** [comment]
Does this still happen if you wait a few seconds before placing the artwork on the easel? It may just be waiting for the map to save properly - I'll see if I can replicate it.

**Comment by mibby** [comment]
It does not seem to update for me at all until the map is triggered an update through clicking / painting it.

**Comment by Fupery** [comment]
This should be fixed in version [2.6](https://www.spigotmc.org/resources/artmap-make-custom-textures-and-paintings-with-no-resource-pack-✍.26667/update?update=157774)
