### ISSUE TITLE
Unable to remove Easel

### ISSUE THREAD

**Issue by sourj** [Fupery/ArtMap#50]
I have artmap on my hub and somebody shot it with a paint ball gun from another plugin and it destroyed the art and glitched the easel now it wont remove the easel and i cant place blocks in front of it its glitched. I made sure this cannot happen again however i cant remove the armor stand now... ive tried using ebutcher and /kill commands nothing works!

**Comment by Fupery** [comment]
If //butcher etc does not work, you will need to start your server without ArtMap enabled, punch the items to delete them, and then restart it with ArtMap enabled.
