### ISSUE TITLE
Recipe Book Breaks the Recipe Guide

### ISSUE THREAD

**Issue by kitokofox** [Fupery/ArtMap#52]
https://puu.sh/wvc5B/1186fec450.png

The newly added recipe book in 1.12 can cause the player to be able to generate items as seen in the recipe guide in artmap.

1. Open Artmap, and select a recipe to view.
2. Open the recipe book in the menu.
3. click one of the recipes in the recipe book.
4. The items from the artmap example recipe get shoved into the player's inventory as if the player put the items there in the first place.

**Comment by Fupery** [comment]
This is a known issue, Spigot doesn't have an event for recipe books yet. I've opened an issue on the Spigot tracker, as soon as the event is added I'll be able to fix this.

**Comment by Fupery** [comment]
Fixed in version 2.6.9
