### ISSUE TITLE
Why can't buy this plugin on spigot?

### ISSUE THREAD

**Issue by hqn21** [Fupery/ArtMap#66]
It just showed me "Sorry, we can not process the data right now. Please try again later."

**Comment by ghost** [comment]
I'm currently having this same issue when trying to pay

**Comment by Momshroom** [comment]
Because the developer went inactive.

**Comment by OpalMoonstride** [comment]
This GitHub is dead, and Fupery is missing. Make issues here, instead: https://gitlab.com/BlockStack/ArtMap
