### ISSUE TITLE
Can't draw some parts when the easel is placed between two chunks

### ISSUE THREAD

**Issue by Ejkim1222** [Fupery/ArtMap#88]
![2024-07-28_13 51 45](https://github.com/user-attachments/assets/92fe7d0c-afeb-4d32-bebe-6df46d8936bb)
As you can see, I can't draw on these white parts

![1](https://github.com/user-attachments/assets/29da94e5-a0bd-4ee7-a290-3dbf465d81cc)
Whenever I try to draw on these areas, these messages occur

![2024-07-28_13 52 13](https://github.com/user-attachments/assets/272a6929-c72a-464e-812d-4eacba9de4f1)
And this is the problem. (I guess) when the easel is placed between two chunks, this bug occurs
So I had to relocate the easel whenever this bug happens

I use this plugin on a public server, (I'm not the host) And the server version is 1.20.1
Thanks

**Comment by OpalMoonstride** [comment]
Hey hun this is the wrong place to look for help. Fupery disappeared years ago. The plugin is maintained on GitLab by different devs. Please fill out the ticket there, and we can help you out. https://gitlab.com/BlockStack/ArtMap/-/issues

**Comment by Ejkim1222** [comment]
thx bro
